trigger:
- master

jobs:
- job: androidJNI
  pool:
    vmImage: 'windows-latest'
    
  steps:
  - script: |
      git submodule update --init --recursive
    displayName: 'Checkout dependencies'
  - script: choco install ninja
    displayName: Install Ninja
  - task: Gradle@2
    inputs:
        workingDirectory: 'TestApp/Source/Android'
        gradleWrapperFile: 'TestApp/Source/Android/gradlew'
        gradleOptions: '-Xmx1536m'
        publishJUnitResults: false
        tasks: 'assembleDebug'
    displayName: 'Build androidJNI'
    
