trigger:
- master

jobs:
- job: androidJNI
  pool:
    vmImage: 'windows-latest'
    
  steps:
  - script: |
      git submodule update --init --recursive
    displayName: 'Checkout dependencies'
  - script: |
      set -eu
      curl -Ls https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-mac.zip -o ninja-mac.zip
      unzip ninja-mac.zip
      sudo cp -v ninja /usr/local/bin/
    displayName: 'Prepare System'
  - task: Gradle@2
    inputs:
        workingDirectory: 'TestApp/Source/Android'
        gradleWrapperFile: 'TestApp/Source/Android/gradlew'
        gradleOptions: '-Xmx1536m'
        publishJUnitResults: false
        tasks: 'assembleDebug'
    displayName: 'Build androidJNI'
    
